# Mainnet config

# Extends the mainnet preset
PRESET_BASE: 'minimal'

# Genesis
# ---------------------------------------------------------------
# Customized
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 128
# Customized
MIN_GENESIS_TIME: 1621504614
# Customized
GENESIS_FORK_VERSION: 0x00004105
# Customized (Results in genesis at Wednesday, 16 June 2021 6:00:00 AM+0000)
GENESIS_DELAY: 60


# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair (Customized)
ALTAIR_FORK_VERSION: 0x01004105
ALTAIR_FORK_EPOCH: 1
# Merge
MERGE_FORK_VERSION: 0x02004105
MERGE_FORK_EPOCH: 2
# Sharding
SHARDING_FORK_VERSION: 0x03000000
SHARDING_FORK_EPOCH: 18446744073709551615

# Merge Transition
# ---------------------------------------------------------------
# TBD, 2**256-2**10 is a placeholder
TERMINAL_TOTAL_DIFFICULTY: 100
# 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
# FAR_FUTURE_EPOCH
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615


# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 6
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 2048


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536


# Deposit contract
# ---------------------------------------------------------------
# Ethereum PoW Mainnet (Customized)
DEPOSIT_CHAIN_ID: 2337002
DEPOSIT_NETWORK_ID: 2337002
DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000
